//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NarayanBharuch.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.InnovativExperiments = new HashSet<InnovativExperiment>();
            this.SapanaKaroSakars = new HashSet<SapanaKaroSakar>();
            this.TeachersGyanstras = new HashSet<TeachersGyanstra>();
            this.ParsamniProjects = new HashSet<ParsamniProject>();
            this.LifeSkillsProjects = new HashSet<LifeSkillsProject>();
            this.CulturalPrograms = new HashSet<CulturalProgram>();
            this.StudentSubjectSeminars = new HashSet<StudentSubjectSeminar>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InnovativExperiment> InnovativExperiments { get; set; }
        public virtual ICollection<SapanaKaroSakar> SapanaKaroSakars { get; set; }
        public virtual ICollection<TeachersGyanstra> TeachersGyanstras { get; set; }
        public virtual ICollection<ParsamniProject> ParsamniProjects { get; set; }
        public virtual ICollection<LifeSkillsProject> LifeSkillsProjects { get; set; }
        public virtual ICollection<CulturalProgram> CulturalPrograms { get; set; }
        public virtual ICollection<StudentSubjectSeminar> StudentSubjectSeminars { get; set; }
    }
}
